version: '3'
services:
  web1:
    environment:
     - FLASK_APP=app.py
     - FLASK_DEBUG=1
     - APP_PORT=5001
    build: .
    ports:
     - "5001:5001"
    volumes:
     - .:/code
  web2:
    environment:
     - FLASK_APP=app.py
     - FLASK_DEBUG=1
     - APP_PORT=5002
    build: .
    ports:
     - "5002:5002"
    volumes:
     - .:/code
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - web1
      - web2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:80"



